<?binding.jca insertEmployee_db.jca?>
<wsdl:definitions name="insertEmployee" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/FileAdapter/fileAdapter/insertEmployee" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/FileAdapter/fileAdapter/insertEmployee" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEmployee">
    <plt:partnerLinkType name="insertEmployee_plt">
        <plt:role name="insertEmployee_role">
            <plt:portType name="tns:insertEmployee_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEmployee" schemaLocation="xsd/insertEmployee_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="EmployeesCollection_msg">
        <wsdl:part name="EmployeesCollection" element="top:EmployeesCollection"/>
    </wsdl:message>
    <wsdl:portType name="insertEmployee_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EmployeesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
